In [ ]:
import pandas as pd

df = pd.read_csv("../data/raw/2024.csv")

print(df.shape)

(3076, 50)
['tourney_id', 'tourney_name', 'surface', 'draw_size', 'tourney_level', 'indoor', 'tourney_date', 'match_num', 'winner_id', 'winner_seed', 'winner_entry', 'winner_name', 'winner_hand', 'winner_ht', 'winner_ioc', 'winner_age', 'winner_rank', 'winner_rank_points', 'loser_id', 'loser_seed', 'loser_entry', 'loser_name', 'loser_hand', 'loser_ht', 'loser_ioc', 'loser_age', 'loser_rank', 'loser_rank_points', 'score', 'best_of', 'round', 'minutes', 'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon', 'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df', 'l_svpt', 'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced']

,tourney_id,tourney_name,surface,draw_size,tourney_level,indoor,tourney_date,match_num,winner_id,winner_seed,...,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
0,2024-339,Brisbane,Hard,32,250,O,20240101,1,D875,2.0,...,5.0,4.0,0.0,86.0,51.0,32.0,21.0,15.0,4.0,8.0
1,2024-339,Brisbane,Hard,32,250,O,20240101,2,AE14,NaN,...,0.0,3.0,2.0,83.0,46.0,38.0,22.0,12.0,2.0,2.0
2,2024-339,Brisbane,Hard,32,250,O,20240101,3,H0BH,NaN,...,2.0,16.0,1.0,62.0,47.0,36.0,6.0,10.0,2.0,4.0

In [ ]:
print(list(df.columns))
df.head(3)

['tourney_id', 'tourney_name', 'surface', 'draw_size', 'tourney_level', 'indoor', 'tourney_date', 'match_num', 'winner_id', 'winner_seed', 'winner_entry', 'winner_name', 'winner_hand', 'winner_ht', 'winner_ioc', 'winner_age', 'winner_rank', 'winner_rank_points', 'loser_id', 'loser_seed', 'loser_entry', 'loser_name', 'loser_hand', 'loser_ht', 'loser_ioc', 'loser_age', 'loser_rank', 'loser_rank_points', 'score', 'best_of', 'round', 'minutes', 'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon', 'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df', 'l_svpt', 'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced']

,tourney_id,tourney_name,surface,draw_size,tourney_level,indoor,tourney_date,match_num,winner_id,winner_seed,...,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
0,2024-339,Brisbane,Hard,32,250,O,20240101,1,D875,2.0,...,5.0,4.0,0.0,86.0,51.0,32.0,21.0,15.0,4.0,8.0
1,2024-339,Brisbane,Hard,32,250,O,20240101,2,AE14,NaN,...,0.0,3.0,2.0,83.0,46.0,38.0,22.0,12.0,2.0,2.0
2,2024-339,Brisbane,Hard,32,250,O,20240101,3,H0BH,NaN,...,2.0,16.0,1.0,62.0,47.0,36.0,6.0,10.0,2.0,4.0

In [ ]:
#1
print(df["tourney_level"].value_counts(dropna=False))
print(df["round"].value_counts(dropna=False))

tourney_level
250    996
M      695
G      508
500    435
D      260
A      103
O       64
F       15
Name: count, dtype: int64
round
R32     896
R16     520
R64     464
R128    416
RR      311
QF      264
SF      136
F        68
BR        1
Name: count, dtype: int64

In [ ]:
#2
for col in ["surface", "indoor", "best_of"]:
    print(df[col].value_counts(dropna=False))
    print()

surface
Hard     1769
Clay      980
Grass     327
Name: count, dtype: int64

indoor
O      2422
I       408
NaN     246
Name: count, dtype: int64

best_of
3    2553
5     523
Name: count, dtype: int64

In [ ]:
#3
cols = ["minutes", "w_ace", "w_svpt", "l_ace", "l_svpt", "winner_rank", "loser_rank"]
print(df[cols].isna().mean().round(3))

minutes        0.040
w_ace          0.020
w_svpt         0.020
l_ace          0.020
l_svpt         0.020
winner_rank    0.008
loser_rank     0.013
dtype: float64

In [ ]:
#4
print(df["tourney_date"].dtype, df["tourney_date"].min(), df["tourney_date"].max())
print(df.duplicated(subset=["tourney_id", "match_num"]).sum())

int64 20240101 20241218
0

In [ ]:
#5
print(df["score"].str.contains("W/O", na=False).sum())
print(df["score"].str.contains("RET", na=False).sum())

20
94

In [14]:
#6 
for lvl in ["A", "O", "F"]:
    print(lvl)
    print(df[df["tourney_level"] == lvl]["tourney_name"].value_counts())
    print()

A
tourney_name
Doha               27
Los Cabos          27
United Cup         25
Next Gen Finals    15
Laver Cup           9
Name: count, dtype: int64

O
tourney_name
Paris Olympics    64
Name: count, dtype: int64

F
tourney_name
ATP Tour Finals    15
Name: count, dtype: int64

In [ ]:

m = df[df["tourney_level"] == "M"]
print(m.groupby("tourney_name").agg(matches=("match_num", "count"), draw=("draw_size", "max")))

                      matches  draw
tourney_name
Canada Masters             55    56
Cincinnati Masters         55    56
Indian Wells Masters       95   128
Madrid Masters             95   128
Miami Masters              95   128
Monte Carlo Masters        55    64
Paris Masters              55    56
Rome Masters               95   128
Shanghai Masters           95    96

In [22]:
print(pd.crosstab(df["tourney_level"], df["indoor"].fillna("missing")))

indoor           I    O  missing
tourney_level
250            216  780        0
500             93  342        0
A               15   88        0
D               14    0      246
F               15    0        0
G                0  508        0
M               55  640        0
O                0   64        0

In [23]:
print(df.duplicated(subset=["tourney_id", "match_num"]).sum())
print(df[(df["best_of"] == 5) & (df["tourney_level"] != "G")]["tourney_level"].value_counts())

0
tourney_level
A    15
Name: count, dtype: int64

In [24]:
g = df[df["tourney_level"] == "G"]
print(g.groupby("tourney_name").agg(matches=("match_num", "count"), draw=("draw_size", "max")))

                 matches  draw
tourney_name
Australian Open      127   128
Roland Garros        127   128
US Open              127   128
Wimbledon            127   128